### ISSUE TITLE
Keep filter info file

### ISSUE THREAD

**Issue by mptrsen** [jlanga/exfi#71]
The Bloom filter is written/copied to the .bf file, but the accompanying .txt file that biobloommaker also outputs seems to be absent. However, [the BioBloomTools documentation notes that the filter file is useless without the info file](https://github.com/bcgsc/biobloom/#a-biobloommaker). It would be prudent to also keep the info file around after `build_baited_bloom_filter`.

**Comment by jlanga** [comment]
biobloom is used only to filter the reads with respect to the transcriptome. That bloom filter is stored in /tmp and erased once it is done.

The filter written by exfi is made with abyss-bloom, which in its first lines contains the necessary information.
